### ISSUE TITLE
Not all namespces being listed in "Logs Namespace Pod Control" Panel 

### ISSUE THREAD

**Issue by cguermi** [nickytd/kubernetes-logging-helm#14]
Hello, 

thank you for you project it helps me a lot ! i have a little issue, in the open-search dashboard i'm not seeing all my namespace only few one are listed in the "Logs Namespace Pod Control" dashboards .

how can i troubleshoot that to be able to monitor all my namespaces logs ?

regard, 
<img width="249" alt="Capture" src="https://user-images.githubusercontent.com/94621862/156388451-72a20917-6aa2-47d4-8f8a-559dade7e044.PNG">

**Comment by nickytd** [comment]
Hi
The field relies on the index pattern created in opensearch-dashboards. You may refresh it from the UI.
In the index pattern the kubernetes.namespace_name field should be "Aggregatable".

The index pattern itself depends on the "containers" index mapping in opensearch. The mapping of kubernetes.namespace_name is "keyword". 

Cheers
Niki

**Comment by cguermi** [comment]
Hi, 
the  kubernetes.namespace_name is ""Aggregatable", however not all namespaces are loaded only few ones,

i'm slightly beginner with opensearch do you have a suggestion on how i can fix that please ?


<img width="294" alt="Capture" src="https://user-images.githubusercontent.com/94621862/156583621-48f62f5a-45d4-42cd-82a2-3f34c52e742f.PNG">

regard,

**Comment by cguermi** [comment]
hi, 

increasing the time frame to 24h doest not resolve my issue still not able to catch all my namespaces and logs ..

maybe a misconfiguration of logstash or fluentbit ?

regard,

**Comment by nickytd** [comment]
Hi,

try to isolate the missing namespace and check if a particular workload in the missing namespace generated a log message. 

Cheers
Niki

**Comment by cguermi** [comment]
hi, 

yes all the missing namespaces are generating logs messages but not reported in the dashboard ..
i cannot figure out the problem, 

maybe we can see together in skype if you have few minutes https://join.skype.com/invite/o1L0NkwGtoNy 

regards,

**Comment by nickytd** [comment]
Hi,

Please continue to investigate the issue. If this is a reproducible scenario then with a bit of invested time the problem should be revealed. Increasing various logs levels of the opensearch and other components may help. You need to pull the chart, adjust various configs and redeploy the components. 
One scenario with a missing log record is when the record is denied of being indexed by the opensearch which may be due to a contradicting index mappings with other records. 
For example: if one record has a field which is mapped to a text by opensearch and other record has the same field mapped as keyword. In such scenarios the opensearch will drop indexing. To overcome such scenario you may need to create a dedicated index with the corresponding index schema mappings. For example the helm chart has the nginx ingress controller logs separated in a dedicated index with it's own schema.
Hope this helps.

Cheers
Niki

**Comment by nickytd** [comment]
Please reopen if problem exists in the latest 4.0.x version
